---
- hosts: tomcat
  remote_user: root
  become_method: sudo
  become: yes
  tasks:
    - name: Install java7
      yum:
        name: java-1.7.0-openjdk
        state: present
    - name: Create Linux Group for Tomcat
      group:
         name: tomcat
    - name: Create Linux User for Tomcat
      user:
         name: tomcat
         groups: 
           - tomcat
           - root  
         home: /usr/share/tomcat
    - name: Download tomcat archive
      get_url:
         url: http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz
         dest: /opt/apache-tomcat-7.0.61.tar.gz
    - name: Unarchive a file that is already on the remote machine
      unarchive:
       src: /opt/apache-tomcat-7.0.61.tar.gz
       dest: /opt/
       remote_src: yes

       #   - name: Change ownership of Tomcat installation
       #     file: path=/opt/apache-tomcat-7.0.61/ owner=tomcat group=tomcat state=directory recurse=yes

    - name: Start Tomcat
      command: nohup sh /opt/apache-tomcat-7.0.61/bin/startup.sh
      become: true


